version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: gymemory_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gymemory_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "81:80"

  web:
    build: ./.docker
    container_name: gymemory_web
    volumes:
      - ./backend:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mysql
