name: CI

on: [push, pull_request]

jobs:
#  build_backend:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.1'
#      - name: Composer install
#        run: cd backend && composer install
#      - name: Run phpstan analysis
#        run: cd backend && ../tools/phpstan.sh
#  build_frontend:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v3
#      - name: Yarn install
#        run: cd frontend && yarn install
#      - name: Run eslint analysis
#        run: cd frontend && ../tools/eslint.sh
  deploy_main_server:
    runs-on: ubuntu-22.04
#    needs: [build_backend, build_frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to live
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: /var/www/gymemory.kasteckis.lt/tools/deploy.sh
